bootstrap_url: http://10.1.50.128:80
cluster_name: bamf
superuser_username: opc
superuser_password_hash: <su hash>
master_discovery: static
exhibitor_storage_backend: static
ip_detect_public_filename: genconf/ip-detect
master_list:
- 10.1.20.2
- 10.1.20.3
- 10.1.20.4
- 10.1.20.5
- 10.1.20.6
resolvers:
- 169.254.169.254
## Choose your security mode: permissive or strict
security: permissive
## A custom proxy is optional. For details, see the configuration documentation.
#use_proxy: 'true'
#http_proxy: http://<user>:<pass>@<proxy_host>:<http_proxy_port>
#https_proxy: https://<user>:<pass>@<proxy_host>:<https_proxy_port>
#no_proxy:
#- 'foo.bar.com'
#- '.baz.com'
## Fault domain entry required for DC/OS Enterprise 1.12+
fault_domain_enabled: false
##If IPv6 is disabled in your kernel, you must disable it in the config.yaml
enable_ipv6: 'false'
#
